FROM php:8.2-fpm

# Atualizar os repositórios e instalar dependências necessárias
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    git \
    curl \
    libzip-dev \
    libmariadb-dev \
    gcc \
    make \
    && rm -rf /var/lib/apt/lists/*

# Configurar extensões PHP
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql zip \
    && pecl install redis \
    && docker-php-ext-enable redis

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Configurar diretório de trabalho
WORKDIR /var/www

# Copiar arquivos essenciais para otimizar cache Docker
COPY composer.json composer.lock ./

# Instalar dependências do PHP
RUN composer install --no-dev --no-scripts --no-autoloader

# Copiar todo o código da aplicação
COPY . .

# Ajustar permissões
RUN composer dump-autoload --optimize \
    && chown -R www-data:www-data /var/www \
    && chmod -R 775 /var/www/storage

# Expor porta 9000 para PHP-FPM
EXPOSE 9000

# Iniciar PHP-FPM
CMD ["php-fpm"]
